version: 2
 
jobs:
    # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
                fingerprints:
                    - ${FINGERPRINT}
            - run:  
                name: Start ssh-keyscan  
                command: |
                    ssh-keyscan -p ${SSH_PORT} ${HOST_NAME} >> ~/.ssh/known_hosts 
            - run:
                name: Pull code  
                command: |
                    ssh -v ${USER_NAME}@${HOST_NAME} 'cd ~/usr/local/src/news_ui && git pull'
 
workflows:
    version: 2
    # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    build_and_deploy:
        # build ジョブと deploy ジョブを呼び出す
        jobs:
            - deploy:
                # master ブランチに push された場合のみ deploy ジョブを実行する
                filters:
                    branches:
                        only: main